const {Given, Then, When, Before} = require('@cucumber/cucumber');

Then(/^cancel booking in Dashboard$/, async () => {
await browser
    // .url('https://test123.bagsawaygo.com/orders')
    // .pause(2000)
    // .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[1]/div[2]/div[2]/button', [3500])
    .click('/html/body/div/div/section/div/div[2]/div[2]/div[2]/div[2]/button')
    .pause(1000)
    .waitForElementVisible('/html/body/div[1]/div/section/div/div[1]/div[1]/div[1]', [3500])
    .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[5]/ul/li[1]/div[1]', [3500])
    .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[5]/ul/li[4]/div[1]', [3500])
    .assert.containsText('/html/body/div[1]/div/section/div/div[1]/div[1]/div[2]', 'Thank you for Booking')
    .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[3]/div[2]', 'Test shop')
    .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[3]/div[3]', 'Lockport Avenue, Toronto, ON, Canada')
    .assert.containsText('/html/body/div[1]/div/section/div/div[3]/div/button[1]', 'Change Booking')
    .click('/html/body/div[1]/div/section/div/div[3]/div/button[1]')
    .pause(2000)
    .waitForElementVisible('/html/body/div[3]/div[3]/div/div[1]', [3500])
    .assert.containsText('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button', 'Cancel This Order')
    .assert.containsText('/html/body/div[3]/div[3]/div/div[2]/button/span[1]', 'Confirm Update')
    .click('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button')
    .pause(2000)
    .waitForElementVisible('/html/body/div[4]/div[3]/div', [3500])
    .assert.containsText('/html/body/div[4]/div[3]/div/div[1]/h2', 'Cancel order?')
    .assert.containsText('/html/body/div[4]/div[3]/div/div[2]/button[1]/span[1]', 'CANCEL')
    .assert.containsText('/html/body/div[4]/div[3]/div/div[2]/button[2]/span[1]', 'ACCEPT')
    .click('/html/body/div[4]/div[3]/div/div[2]/button[1]')
    .pause(2000)
    .assert.containsText('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button/span[1]', 'Cancel This Order')
    .click('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button')
    .pause(2000)
    .waitForElementVisible('/html/body/div[4]/div[3]/div', [3500])
    .assert.containsText('/html/body/div[4]/div[3]/div/div[2]/button[2]/span[1]', 'ACCEPT')
    .click('/html/body/div[4]/div[3]/div/div[2]/button[2]')
    .pause(2000)
    .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[5]/ul/li[4]/div[2]/div[2]', [3500])
    .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[3]', 'This Order has been Cancelled')
    .click('/html/body/div[1]/div/section/div/div[3]/div/a/span[1]')
    .pause(2000)
    .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[2]/div[2]', [3500])
    .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[2]/div[3]', 'Canceled Reservation');
});

Then(/^cancel booking after book$/, async () => {
    await browser
        .click('/html/body/div[1]/div/div[1]/div/div[2]/div/div[4]/span/span[1]/input')
        .pause(500)
        .click('/html/body/div[1]/div/div[1]/div/div[3]/button')
        .pause(500)
        .waitForElementVisible('/html/body/div[1]/div/section/div/div[1]/div[1]', [3500])
        .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[5]/ul/li[1]/div[1]', [3500])
        .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[7]/div/div[1]', 'You booked just in time!')
        .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[7]/div/div[2]',
            'This BagDrop Location has limited space!')
        .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[8]/div/div[1]', 'Store Hours')
        .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[8]/div/div[2]', 'Test shop')
        .assert.containsText('/html/body/div[1]/div/section/div/div[3]/div/button[1]', 'Change Booking')
        .assert.containsText('/html/body/div/div/section/div/div[3]/div/a/span[1]', 'Dashboard')
        .click('/html/body/div[1]/div/section/div/div[3]/div/button[1]')
        .waitForElementVisible('/html/body/div[3]/div[3]/div', [3500])
        .assert.containsText('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button/span[1]', 'Cancel This Order')
        .click('/html/body/div[3]/div[3]/div/div[1]/div[2]/div/button')
        .waitForElementVisible('/html/body/div[4]/div[3]/div', [3500])
        .assert.containsText('/html/body/div[4]/div[3]/div/div[2]/button[2]', 'ACCEPT')
        .click('/html/body/div[4]/div[3]/div/div[2]/button[2]')
        .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[5]/ul/li[4]/div[2]/div[2]', [3500])
        .assert.containsText('/html/body/div[1]/div/section/div/div[2]/div[3]', 'This Order has been Cancelled')
        .click('/html/body/div/div/section/div/div[3]/div/a')
        .waitForElementVisible('/html/body/div[1]/div/section/div/div[2]/div[1]', [3500])
        .assert.containsText('/html/body/div/div/section/div/div[2]/div[2]/div[3]', 'Canceled Reservation');
});
